### ISSUE TITLE
Missing tests in .gem file

### ISSUE THREAD

**Issue by mdb571** [k0kubun/activerecord-precounter#10]
Can we include the tests as part of the gem itself ? I'm packaging this library for debian and I have to take a github tarball instead of the gem from rubygems.org . So it would be better if the test is available with the gem itself :)

**Comment by k0kubun** [comment]
Thanks for working on packaging this.

I don't get why you're asking this. It's not something specific to this repository, but it's the behavior of the code generated by "bundle gem" that the gem package doesn't include test suite. Are you asking this to every single rubygems you're packaging? Is there any example well-known gem that opts in tests just for supporting tests in debian packages? Are you really interested in installing and running PostgreSQL to run the test suite on installed machines?

**Comment by mdb571** [comment]
Thanks for the quick reply . Generally debian prefers testing packages before uploading it to the archive and It is considered a best practice to ask the author if it can be included in the upstream repository .Also I don't know if I can show you a well-known gem that opts in tests just for supporting debian (dunno if there is one.. only someone experienced than myself can answer this) Alternatively I can download the github tarball using tags for preparing the package . I understand that things might get difficult for people using the gem if you include tests. 
Anyways thanks for clarifying and hoping to get this packaged :)

**Comment by k0kubun** [comment]
> Alternatively I can download the github tarball using tags for preparing the package.

I'm guessing this is what people end up doing. I know there's a debian package for another gem of mine, https://github.com/k0kubun/hamlit, which has way more users than this gem, but that also excludes tests from the gem package.

Could you try that way for now? Thank you.
