### ISSUE TITLE
problem with 0.2.1/AR 4.2.10

### ISSUE THREAD

**Issue by argent-smith** [k0kubun/activerecord-precounter#3]
Hi. It fell out of my tests when I've upgraded version to 0.2.1 (0.2.0 worked fine), AR version is 4.2.10:

```
Users Update User updates user
     Failure/Error: ActiveRecord::Precounter.new(@resources).precount(:alive_client_user_roles)

     NoMethodError:
       undefined method `has_scope?' for #<ActiveRecord::Reflection::HasManyReflection:0x00005562232b0810>
       Did you mean?  has_one?
```

Any suggestions?

**Comment by k0kubun** [comment]
It seems like due to https://github.com/k0kubun/activerecord-precounter/pull/2. Probably we need to add version guard inside code or version requirement in gemspec. If you don't need scope support, you can use 0.2.0 for now.

**Comment by k0kubun** [comment]
For now we dropped support of 4.2. It may not be so difficult to resurrect the support, but as it's not in the supported matrix, let me close this for now.
